name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ env.SSH_KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy to EC2
        run: ssh -i ~/.ssh/staging.key -o StrictHostKeyChecking=no ubuntu@ec2-35-85-46-253.us-west-2.compute.amazonaws.com 'bash -s' < ./.scripts/deploy.sh
